version: '3.9'
services:
  mariadb:
    networks:
      - web-dev
    environment:
        MARIADB_ROOT_PASSWORD: "bitproject22"
        MARIADB_DATABASE: "inventaprobd"
        MARIADB_USER: "rootbit"
        MARIADB_PASSWORD: "invbitproject"
    volumes:
      # Add volume for all database files
      - ./_volumes/mysql/database_data/:/var/lib/mysql
      # Add volume for custom configurations
      - ./_volumes/mysql/conf.d/:/etc/mysql/conf.d
      - ./_volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - target: 3306
        published: 3306
        mode: host
  php:
    networks:
        - web-dev
    ports:
      # Listen on port 80, default for HTTP
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
    volumes:
      - .:/var/www/html/:cached
    depends_on:
      - "mariadb"
  node:
    networks:
      - web-dev
    volumes:
      - .:/usr/src/app/:cached
    working_dir: /usr/src/app/
networks:
  web-dev:
