version: '3.9'
services:
  mariadb:
    image: mariadb:10.7
    container_name: mariabd_inv
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/bd/acculance.sql:/docker-entrypoint-initdb.d/inventapro.sql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - 'mariadb-data:/var/lib/mysql'
    networks:
      - default
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  app:
    image: bitinv2
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.n8n-secure.entrypoints=websecure"
      - "traefik.http.routers.n8n-secure.rule=Host(`bitproject.inventapro.com`)"
      - "traefik.http.services.n8n-websocket.loadbalancer.server.port=8001"
    env_file:
      - .env.prod
    volumes:
      - ./storage:/app/storage
    ports:
      - "8001:80"
    restart: always
    networks:
      - default
  redis:
    image: redis:6
    volumes:
      - 'data.redis:/data'
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  mariadb-data:
  data.redis:
networks:
  default:
    external: true
    name: core_proxy
