version: '3.9'
services:
  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/Providers:/var/www/app/Providers/
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - mariadb
    networks:
      - default
  mariadb:
    image: mariadb:10.7
    container_name: mariabd_inv
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/bd/acculance.sql:/docker-entrypoint-initdb.d/inventapro.sql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - 'mariadb-data:/var/lib/mysql'
    networks:
      - default
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
    #   retries: 3
    #   timeout: 5s
  app:
    build:
      args:
        user: bitusr
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: inventaprophp
    container_name: inventaprophp
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/Providers:/var/www/app/Providers/
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - default
  # node:
  #   image: node:15-alpine
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
  #     - /var/www/node_modules
  #   command: sh /var/www/node_start.sh
  #   depends_on:
  #     - app
  redis:
    image: redis:6
    volumes:
      - 'data.redis:/data'
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  mariadb-data:
    driver: local
  data.redis:
    driver: local
networks:
  default:
    driver: bridge
# version: '3.9'
# services:
#   php:
#     image: serversideup/php:8.1-fpm-nginx
#     working_dir: /var/www/html

#   mariadb:
#     image: mariadb:10.7

#   node:
#     image: node:lts
